{{- $refreshPeriod := "240h" }}

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/fzf-git"]
    type = "archive"
    url = "https://github.com/junegunn/fzf-git.sh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $fzfmarksVersion := "1.1" -}}
[".oh-my-zsh/custom/plugins/fzf-marks"]
    type = "archive"
    url = "https://github.com/urbainvaes/fzf-marks/archive/refs/tags/{{$fzfmarksVersion}}.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $kubetailVersion := "1.6.20" -}}
[".oh-my-zsh/custom/plugins/kubetail"]
    type = "archive"
    url = "https://github.com/johanhaleby/kubetail/archive/refs/tags/{{$kubetailVersion}}.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/completion/_kubetail.zsh"]
    type = "archive-file"
    url = "https://github.com/johanhaleby/kubetail/archive/refs/tags/{{$kubetailVersion}}.tar.gz"
    path = "kubetail-{{$kubetailVersion}}/completion/kubetail.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $pluggedVersion := "0.14.0" -}}
[".vim/autoload/plug.vim"]
    type = "archive-file"
    url = "https://github.com/junegunn/vim-plug/archive/refs/tags/{{$pluggedVersion}}.tar.gz"
    stripComponents = 1
    path = "plug.vim"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $superfileVersion := "1.1.4" -}}
["bin/spf"]
    type = "archive-file"
    url = "https://github.com/yorukot/superfile/releases/download/v{{$superfileVersion}}/superfile-{{$.chezmoi.os}}-v{{$superfileVersion}}-{{$.chezmoi.arch}}.tar.gz"
    stripComponents = 3
    path = "spf"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $qsvVersion := "0.134.0" -}}
["bin/qsv"]
    type = "archive-file"
    url = "https://github.com/jqnatividad/qsv/releases/download/{{$qsvVersion}}/qsv-{{$qsvVersion}}-x86_64-unknown-{{$.chezmoi.os}}-gnu.zip"
    path = "qsvpy312"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $ovVersion := "0.36.0" -}}
["bin/ov"]
    type = "archive-file"
    url = "https://github.com/noborus/ov/releases/download/v{{$ovVersion}}/ov_{{$ovVersion}}_{{$.chezmoi.os}}_{{$.chezmoi.arch}}.zip"
    path = "ov"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $diveVersion := "0.12.0" -}}
["bin/dive"]
    type = "archive-file"
    url = "https://github.com/wagoodman/dive/releases/download/v{{$diveVersion}}/dive_{{$diveVersion}}_{{$.chezmoi.os}}_{{$.chezmoi.arch}}.tar.gz"
    path = "dive"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $jqpVersion := "0.7.0" -}}
["bin/jqp"]
    type = "archive-file"
    url = "https://github.com/noahgorstein/jqp/releases/download/v{{$jqpVersion}}/jqp_{{$.chezmoi.os}}_x86_64.tar.gz"
    path = "jqp"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $sternVersion := "1.30.0" -}}
["bin/stern"]
    type = "archive-file"
    url = "https://github.com/stern/stern/releases/download/v{{$sternVersion}}/stern_{{$sternVersion}}_{{.chezmoi.os}}_{{.chezmoi.arch}}.tar.gz"
    path = "stern"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $kubectxVersion := "0.9.5" -}}
["bin/kubectx"]
    type = "archive-file"
    url = "https://github.com/ahmetb/kubectx/releases/download/v{{$kubectxVersion}}/kubectx_v{{$kubectxVersion}}_{{.chezmoi.os}}_x86_64.tar.gz"
    path = "kubectx"
    refreshPeriod = "{{ $refreshPeriod }}"


{{ $k9sVersion := "0.32.5" -}}
["bin/k9s"]
    type = "archive-file"
    url = "https://github.com/derailed/k9s/releases/download/v{{$k9sVersion}}/k9s_Linux_{{.chezmoi.arch}}.tar.gz"
    path = "k9s"
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/completion/_kubectx.zsh"]
    type = "archive-file"
    url = "https://github.com/ahmetb/kubectx/archive/refs/tags/v{{$kubectxVersion}}.tar.gz"
    path = "kubectx-{{$kubectxVersion}}/completion/_kubectx.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"

