{{- $refreshPeriod := "240h" }}

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/fzf-git"]
    type = "archive"
    url = "https://github.com/junegunn/fzf-git.sh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $fzfmarksVersion := "1.1" -}}
[".oh-my-zsh/custom/plugins/fzf-marks"]
    type = "archive"
    url = "https://github.com/urbainvaes/fzf-marks/archive/refs/tags/{{$fzfmarksVersion}}.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $kubetailVersion := "1.6.20" -}}
[".oh-my-zsh/custom/plugins/kubetail"]
    type = "archive"
    url = "https://github.com/johanhaleby/kubetail/archive/refs/tags/{{$kubetailVersion}}.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/completion/_kubetail.zsh"]
    type = "archive-file"
    url = "https://github.com/johanhaleby/kubetail/archive/refs/tags/{{$kubetailVersion}}.tar.gz"
    path = "kubetail-{{$kubetailVersion}}/completion/kubetail.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $pluggedVersion := "0.13.0" -}}
[".vim/autoload/plug.vim"]
    type = "archive-file"
    url = "https://github.com/junegunn/vim-plug/archive/refs/tags/{{$pluggedVersion}}.tar.gz"
    stripComponents = 1
    path = "plug.vim"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $diveVersion := "0.12.0" -}}
["bin/dive"]
    type = "archive-file"
    url = "https://github.com/wagoodman/dive/releases/download/v{{$diveVersion}}/dive_{{$diveVersion}}_{{$.chezmoi.os}}_{{$.chezmoi.arch}}.tar.gz"
    path = "dive"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $sternVersion := "1.30.0" -}}
["bin/stern"]
    type = "archive-file"
    url = "https://github.com/stern/stern/releases/download/v{{$sternVersion}}/stern_{{$sternVersion}}_{{.chezmoi.os}}_{{.chezmoi.arch}}.tar.gz"
    path = "stern"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $kubectxVersion := "0.9.5" -}}
["bin/kubectx"]
    type = "archive-file"
    url = "https://github.com/ahmetb/kubectx/releases/download/v{{$kubectxVersion}}/kubectx_v{{$kubectxVersion}}_{{.chezmoi.os}}_x86_64.tar.gz"
    path = "kubectx"
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/completion/_kubectx.zsh"]
    type = "archive-file"
    url = "https://github.com/ahmetb/kubectx/archive/refs/tags/v{{$kubectxVersion}}.tar.gz"
    path = "kubectx-{{$kubectxVersion}}/completion/_kubectx.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"

