{{- $refreshPeriod := "240h" }}

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    # exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/fzf-git"]
    type = "archive"
    url = "https://github.com/junegunn/fzf-git.sh/archive/master.tar.gz"
    exact = true
    stripComponents = 1

{{ $kubetailVersion := "1.6.18" -}}
[".oh-my-zsh/custom/plugins/kubetail"]
    type = "archive"
    url = "https://github.com/johanhaleby/kubetail/archive/refs/tags/{{$kubetailVersion}}.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $pluggedVersion := "0.11.0" -}}
[".vim/autoload/plug.vim"]
    type = "archive-file"
    url = "https://github.com/junegunn/vim-plug/archive/refs/tags/{{$pluggedVersion}}.tar.gz"
    stripComponents = 1
    path = "plug.vim"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $sternVersion := "1.25.0" -}}
["bin/stern"]
    type = "archive-file"
    url = "https://github.com/stern/stern/releases/download/v{{$sternVersion}}/stern_{{$sternVersion}}_{{.chezmoi.os}}_{{.chezmoi.arch}}.tar.gz"
    path = "stern"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $kubectxVersion := "0.9.5" -}}
["bin/kubectx"]
    type = "archive-file"
    url = "https://github.com/ahmetb/kubectx/releases/download/v{{$kubectxVersion}}/kubectx_v{{$kubectxVersion}}_{{.chezmoi.os}}_x86_64.tar.gz"
    path = "kubectx"
    refreshPeriod = "{{ $refreshPeriod }}"
