{{- $refreshPeriod := "240h" }}

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/fzf-git"]
    type = "archive"
    url = "https://github.com/junegunn/fzf-git.sh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $fzfmarksVersion := "1.1" -}}
[".oh-my-zsh/custom/plugins/fzf-marks"]
    type = "archive"
    url = "https://github.com/urbainvaes/fzf-marks/archive/refs/tags/{{$fzfmarksVersion}}.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $pluggedVersion := "0.14.0" -}}
[".vim/autoload/plug.vim"]
    type = "archive-file"
    url = "https://github.com/junegunn/vim-plug/archive/refs/tags/{{$pluggedVersion}}.tar.gz"
    stripComponents = 1
    path = "plug.vim"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $superfileVersion := "1.1.7" -}}
["bin/spf"]
    type = "archive-file"
    url = "https://github.com/yorukot/superfile/releases/download/v{{$superfileVersion}}/superfile-{{$.chezmoi.os}}-v{{$superfileVersion}}-{{$.chezmoi.arch}}.tar.gz"
    stripComponents = 3
    path = "spf"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $qsvVersion := "0.134.0" -}}
["bin/qsv"]
    type = "archive-file"
    url = "https://github.com/jqnatividad/qsv/releases/download/{{$qsvVersion}}/qsv-{{$qsvVersion}}-x86_64-unknown-{{$.chezmoi.os}}-gnu.zip"
    path = "qsvpy312"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $ovVersion := "0.36.0" -}}
["bin/ov"]
    type = "archive-file"
    url = "https://github.com/noborus/ov/releases/download/v{{$ovVersion}}/ov_{{$ovVersion}}_{{$.chezmoi.os}}_{{$.chezmoi.arch}}.zip"
    path = "ov"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $jqpVersion := "0.7.0" -}}
["bin/jqp"]
    type = "archive-file"
    url = "https://github.com/noahgorstein/jqp/releases/download/v{{$jqpVersion}}/jqp_{{$.chezmoi.os}}_x86_64.tar.gz"
    path = "jqp"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $hoardVersion := "1.4.2" -}}
[".oh-my-zsh/custom/hoard.zsh"]
    type = "archive-file"
    url = "https://github.com/Hyde46/hoard/archive/refs/tags/v{{$hoardVersion}}.zip"
    path = "hoard-{{$hoardVersion}}/src/shell/hoard.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $lazygitVersion := "0.52.0" -}}
["bin/lazygit"]
    type = "archive-file"
    executable = true
    url = "https://github.com/jesseduffield/lazygit/releases/download/v{{$lazygitVersion}}/lazygit_{{$lazygitVersion}}_{{.chezmoi.os | title}}_x86_64.tar.gz"
    path = "lazygit"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ if eq .chezmoi.osRelease.id "fedora" -}}
{{ $diveVersion := "0.12.0" -}}
["bin/dive"]
    type = "archive-file"
    url = "https://github.com/wagoodman/dive/releases/download/v{{$diveVersion}}/dive_{{$diveVersion}}_{{$.chezmoi.os}}_{{$.chezmoi.arch}}.tar.gz"
    path = "dive"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $sternVersion := "1.30.0" -}}
["bin/stern"]
    type = "archive-file"
    url = "https://github.com/stern/stern/releases/download/v{{$sternVersion}}/stern_{{$sternVersion}}_{{.chezmoi.os}}_{{.chezmoi.arch}}.tar.gz"
    path = "stern"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $kubetailVersion := "1.6.20" -}}
[".oh-my-zsh/custom/plugins/kubetail"]
    type = "archive"
    url = "https://github.com/johanhaleby/kubetail/archive/refs/tags/{{$kubetailVersion}}.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/completion/_kubetail.zsh"]
    type = "archive-file"
    url = "https://github.com/johanhaleby/kubetail/archive/refs/tags/{{$kubetailVersion}}.tar.gz"
    path = "kubetail-{{$kubetailVersion}}/completion/kubetail.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $kubectxVersion := "0.9.5" -}}
["bin/kubectx"]
    type = "archive-file"
    url = "https://github.com/ahmetb/kubectx/releases/download/v{{$kubectxVersion}}/kubectx_v{{$kubectxVersion}}_{{.chezmoi.os}}_x86_64.tar.gz"
    path = "kubectx"
    refreshPeriod = "{{ $refreshPeriod }}"

[".oh-my-zsh/custom/completion/_kubectx.zsh"]
    type = "archive-file"
    url = "https://github.com/ahmetb/kubectx/archive/refs/tags/v{{$kubectxVersion}}.tar.gz"
    path = "kubectx-{{$kubectxVersion}}/completion/_kubectx.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $klVersion := "0.4.0" -}}
["bin/kl"]
    type = "archive-file"
    url = "https://github.com/robinovitch61/kl/releases/download/v{{$klVersion}}/kl_{{$klVersion}}_{{.chezmoi.os | title}}_x86_64.tar.gz"
    path = "kl"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $k9sVersion := "0.50.6" -}}
["bin/k9s"]
    type = "archive-file"
    url = "https://github.com/derailed/k9s/releases/download/v{{$k9sVersion}}/k9s_{{.chezmoi.os | title}}_{{.chezmoi.arch}}.tar.gz"
    path = "k9s"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $kplayVersion := "0.1.0" -}}
["bin/kplay"]
    type = "archive-file"
    url = "https://github.com/dhth/kplay/releases/download/v{{$kplayVersion}}/kplay_{{$kplayVersion}}_{{.chezmoi.os}}_{{.chezmoi.arch}}.tar.gz"
    path = "kplay"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $lazyjournalVersion := "0.5.0" -}}
["bin/lazyjournal"]
    type = "file"
    executable = true
    url = "https://github.com/Lifailon/lazyjournal/releases/download/{{$lazyjournalVersion}}/lazyjournal-{{$lazyjournalVersion}}-{{.chezmoi.os}}-{{.chezmoi.arch}}"
    refreshPeriod = "{{ $refreshPeriod }}"

{{ $trivyVersion := "0.60.0" -}}
["bin/trivy"]
    type = "archive-file"
    executable = true
    url = "https://github.com/aquasecurity/trivy/releases/download/v{{$trivyVersion}}/trivy_{{$trivyVersion}}_{{.chezmoi.os | title}}-64bit.tar.gz"
    path = "trivy"
    refreshPeriod = "{{ $refreshPeriod }}"

["bin/trivy-contrib"]
    type = "archive"
    url = "https://github.com/aquasecurity/trivy/releases/download/v{{$trivyVersion}}/trivy_{{$trivyVersion}}_{{.chezmoi.os | title}}-64bit.tar.gz"
    path = "contrib"
    stripComponents = 1
    include = ["**/*.tpl"]
    refreshPeriod = "{{ $refreshPeriod }}"
{{ end -}}
