#! /bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Don't run this hook if Tito is making a commit
if git diff --cached --name-only --diff-filter=M -z $against | grep -q 'rel-eng/packages'; then
    exit 0
fi

# Git hooks don't normally accept stdin so use a bit of
# hackery to assign stdin to the keyboard
exec < /dev/tty
while true; do
    read -p "Did you run the unit tests and style checker? (y/n) " yn
    if [ "$yn" = "" ]; then
        yn='Y'
    fi
    case $yn in
        [Yy] ) exit 0;;
        [Nn] ) exit 1;;
        * ) echo "Please answer y or n for yes or no.";;
    esac
done
